package logitech

const LOGI_MAX_CONTROLLERS int = 4

//Force types

const LOGI_FORCE_NONE int = -1
const LOGI_FORCE_SPRING int = 0
const LOGI_FORCE_CONSTANT int = 1
const LOGI_FORCE_DAMPER int = 2
const LOGI_FORCE_SIDE_COLLISION int = 3
const LOGI_FORCE_FRONTAL_COLLISION int = 4
const LOGI_FORCE_DIRT_ROAD int = 5
const LOGI_FORCE_BUMPY_ROAD int = 6
const LOGI_FORCE_SLIPPERY_ROAD int = 7
const LOGI_FORCE_SURFACE_EFFECT int = 8
const LOGI_NUMBER_FORCE_EFFECTS int = 9
const LOGI_FORCE_SOFTSTOP int = 10
const LOGI_FORCE_CAR_AIRBORNE int = 11

//Periodic types  for surface effect

const LOGI_PERIODICTYPE_NONE int = -1
const LOGI_PERIODICTYPE_SINE int = 0
const LOGI_PERIODICTYPE_SQUARE int = 1
const LOGI_PERIODICTYPE_TRIANGLE int = 2

//Devices types

const LOGI_DEVICE_TYPE_NONE int = -1
const LOGI_DEVICE_TYPE_WHEEL int = 0
const LOGI_DEVICE_TYPE_JOYSTICK int = 1
const LOGI_DEVICE_TYPE_GAMEPAD int = 2
const LOGI_DEVICE_TYPE_OTHER int = 3
const LOGI_NUMBER_DEVICE_TYPES int = 4

//Manufacturer types

const LOGI_MANUFACTURER_NONE int = -1
const LOGI_MANUFACTURER_LOGITECH int = 0
const LOGI_MANUFACTURER_MICROSOFT int = 1
const LOGI_MANUFACTURER_OTHER int = 2

//Model types

const LOGI_MODEL_G27 int = 0
const LOGI_MODEL_DRIVING_FORCE_GT int = 1
const LOGI_MODEL_G25 int = 2
const LOGI_MODEL_MOMO_RACING int = 3
const LOGI_MODEL_MOMO_FORCE int = 4
const LOGI_MODEL_DRIVING_FORCE_PRO int = 5
const LOGI_MODEL_DRIVING_FORCE int = 6
const LOGI_MODEL_NASCAR_RACING_WHEEL int = 7
const LOGI_MODEL_FORMULA_FORCE int = 8
const LOGI_MODEL_FORMULA_FORCE_GP int = 9
const LOGI_MODEL_FORCE_3D_PRO int = 10
const LOGI_MODEL_EXTREME_3D_PRO int = 11
const LOGI_MODEL_FREEDOM_24 int = 12
const LOGI_MODEL_ATTACK_3 int = 13
const LOGI_MODEL_FORCE_3D int = 14
const LOGI_MODEL_STRIKE_FORCE_3D int = 15
const LOGI_MODEL_G940_JOYSTICK int = 16
const LOGI_MODEL_G940_THROTTLE int = 17
const LOGI_MODEL_G940_PEDALS int = 18
const LOGI_MODEL_RUMBLEPAD int = 19
const LOGI_MODEL_RUMBLEPAD_2 int = 20
const LOGI_MODEL_CORDLESS_RUMBLEPAD_2 int = 21
const LOGI_MODEL_CORDLESS_GAMEPAD int = 22
const LOGI_MODEL_DUAL_ACTION_GAMEPAD int = 23
const LOGI_MODEL_PRECISION_GAMEPAD_2 int = 24
const LOGI_MODEL_CHILLSTREAM int = 25
const LOGI_MODEL_G29 int = 26
const LOGI_MODEL_G920 int = 27
const LOGI_NUMBER_MODELS int = 28
